### ISSUE TITLE
Question about Identity Assignment

### ISSUE THREAD

**Issue by 9p15p** [yoxu515/aot-benchmark#23]
Hi, Dr. Yang:
It seems very useful to use identity assignment.

Although I have read the paper and code, but I can't understand how it works yet. 
it seems AOT only use a very simple convolution to produce a `id_emb`.
https://github.com/yoxu515/aot-benchmark/blob/5a7665fc8e0f0e64bc8ba6028b15d9ab32f4c56a/networks/models/aot.py#L76

Then, add this `id_emb` in to 
https://github.com/yoxu515/aot-benchmark/blob/5a7665fc8e0f0e64bc8ba6028b15d9ab32f4c56a/networks/layers/transformer.py#L216
it will fix the relationship between channels and objects directly. 

It is very interesting and could you please offer more details and proofs about it.

Thank you.

**Comment by z-x-yang** [comment]
The weight of the convolutional layer is just the ID bank described in the paper. The weight shape here should be C*(M+1)*ks*ks. If ks=1, the weight is exactly the described M*C ID bank with an additional ID for background. In the implementation, I set ks>1 with a stride of 16 in order to downsample the ID embedding simultaneously, for the sake of efficiency.

As to the addition process of id_emb, it's simple yet effective. I suppose this works just like how the commonly-used positional encoding works. The embedding space is highly-dimensional enough to contain visual and ID/positional informations.
