### ISSUE TITLE
VOT2020 Performance

### ISSUE THREAD

**Issue by botaoye** [yoxu515/aot-benchmark#32]
Hi authors, I notice that you have mentioned the results on [VOT2020 benchmark](https://paperswithcode.com/sota/semi-supervised-video-object-segmentation-on-15?p=decoupling-features-in-hierarchical). Is the model the same as the model in your paper and which model from the [model zoo](https://github.com/yoxu515/aot-benchmark/blob/main/MODEL_ZOO.md) do you use to evaluate it?

**Comment by z-x-yang** [comment]
For each AOT/DeAOT variant, we used the same checkpoint to evaluate DAVIS, YouTube-VOS, and VOT 2020.

**Comment by botaoye** [comment]
Hi, I tried to run DeAOTS on VOT2020 (keeping only the latest 10 long-term memories), but EAO lags behind the performance you mentioned to a large extent (0.567 vs 0.593). Can you provide more information on how to change other hyperparameters when evaluating on VOT?

**Comment by z-x-yang** [comment]
To perform evaluation on VOT 2020, we slightly modified DeAOT inference codes. 

1) The [short_term_mem_skip](https://github.com/yoxu515/aot-benchmark/blob/1c3a5ec51d81f3e17ff9092aa1e830206d766132/networks/engines/deaot_engine.py#L62) is set to 4 (not sure about the number, I'll check on this) instead of 1, which means the short-term memory comes from the t-4 frame instead of t-1. It's an effective trick to improve the performance because the frame rate of VOT (24fps~30fps) is higher than YouTube-VOS (6fps) and the inter-frame motion is smaller. 

2) Since the sequences in VOT 2020 may have thousands of frames, we set a maximum number of long-term memory frames, such as 10. If the total frame number of long-term memory is larger than the maximum number after updating the memory, we will drop the oldest frame (except for the first reference frame, which will be kept persistently) directly to ensure the long-term memory has a limited size. Such a simple manner can solve the OOM problem of DeAOT-L (but will not affect DeAOT-T/S/B, which won't update the long-term memory) and slightly improve the accuracy of tracking and segmentation.

Based on these modifications, we won two champions in [the Visual Object Tracking (VOT) 2022 challenge](https://www.votchallenge.net/vot2022/trackers.html). The source code of our tracker can be downloaded from [here](http://data.votchallenge.net/vot2022/trackers/MS_AOT-code-2022-05-04T08_08_40.403273.zip).

**Comment by botaoye** [comment]
> 

Got it, thanks a lot.
