### ISSUE TITLE
F score over the boundaries

### ISSUE THREAD

**Issue by bhack** [yoxu515/aot-benchmark#34]
It could be nice to  have the F score for the boundaries other the IOU in `utils/metrics`.

**Comment by z-x-yang** [comment]
Thanks. A good suggestion, we'll work on this.

**Comment by bhack** [comment]
If you are interested I have replicated boundaries extraction reference implementation of BoundaryIOU in Pytorch:

https://github.com/Lightning-AI/metrics/issues/1500#issuecomment-1433162536

**Comment by z-x-yang** [comment]
Thank you for your suggestion. I have reviewed the implementation method in the link you provided, and while it is indeed a good approach, it cannot be directly applied to the AOT code. This is because the calculation of IOU in the aot-benchmark uses multi-object masks rather than binary masks. However, I will implement a multi-target version in recent weeks.

**Comment by bhack** [comment]
That one was only the mask to boundaries then In the official boundary IOU it was just looped over annotations masks:

 https://github.com/bowenc0221/boundary-iou-api/blob/master/boundary_iou/utils/boundary_utils.py#L37-L38
