### ISSUE TITLE
CUDA out of memory

### ISSUE THREAD

**Issue by whxueChris** [yoxu515/aot-benchmark#44]
Hello! 
I used the `python eval.py --stage pre_dav --model r50_aotl --ckpt_path ./pretrain_models/R50_AOTL_PRE_YTB_DAV.pth` to evaluate my own dataset (following DAVIS format 480p), and it encountered cuda out of memory issue. 
![image](https://github.com/yoxu515/aot-benchmark/assets/50388024/386e8945-17c2-49a6-8846-275ca1b8786f)

Could you give me some suggestions for how to reduce the memory?

Thank you!

**Comment by yoxu515** [comment]
It is because AOT-L models dynamically add new frames to memory every 5 frames by default, while other models like AOT-B or AOT-S only use the first frame and the previous frame as memory.
You can try modifying self.TEST_LONG_TERM_MEM_GAP = 5 in the config to a larger value.
As for a better solution, a max length of the memory can be set, as described [here](https://github.com/yoxu515/aot-benchmark/issues/32#issuecomment-1437243637).

**Comment by whxueChris** [comment]
> It is because AOT-L models dynamically add new frames to memory every 5 frames by default, while other models like AOT-B or AOT-S only use the first frame and the previous frame as memory. You can try modifying self.TEST_LONG_TERM_MEM_GAP = 5 in the config to a larger value. As for a better solution, a max length of the memory can be set, as described [here](https://github.com/yoxu515/aot-benchmark/issues/32#issuecomment-1437243637).

Thank you!  I have solved this problem.
